import { 
  ExportOrder, 
  Notification, 
  Task, 
  Payment, 
  DocType,
  OrderStage
} from '../lib/types';
import { 
  createDocument, 
  getDocuments, 
  updateDocument 
} from './db';
import { Timestamp } from 'firebase/firestore';
import { generateDocument } from '../lib/documentGenerator';
import { zohoMailService } from './zohoMailService';

/**
 * Service to handle automated workflows and alerts
 */
export const automationService = {
  /**
   * Processes automations triggered by order stage changes
   */
  async processOrderStageChange(order: ExportOrder, oldStage: OrderStage, newStage: OrderStage) {
    if (oldStage === newStage) return;

    const automations: Promise<any>[] = [];

    // 1. Smart Documentation Triggers
    if (newStage === 'orderConfirmed') {
      automations.push(this.autoGenerateDoc(order, 'proformaInvoice'));
    } else if (newStage === 'production') {
      automations.push(this.autoGenerateDoc(order, 'packingList'));
      automations.push(this.scheduleQualityTest(order));
    } else if (newStage === 'shipped') {
      automations.push(this.autoGenerateDoc(order, 'commercialInvoice'));
      automations.push(this.autoGenerateDoc(order, 'gstInvoice'));
      // Auto-send email to buyer when shipped
      automations.push(this.autoSendShipmentEmail(order));
    }

    // 2. Bottleneck Reset
    // When stage changes, we can log the transition for future bottleneck analysis
    automations.push(this.logStageTransition(order, oldStage, newStage));

    await Promise.all(automations);
  },

  /**
   * Auto-generates a document and saves it to the order
   */
  async autoGenerateDoc(order: ExportOrder, type: DocType) {
    try {
      // Check if document already exists to avoid duplicates
      const existingDocs = order.documents || [];
      if (existingDocs.some(d => d.type === type)) return;

      const htmlContent = generateDocument(type, order);
      
      const newDoc = {
        orderId: order.id,
        documentType: type,
        generatedAt: Timestamp.now(),
        generatedBy: 'System Automation',
        htmlContent,
        status: 'draft' as const,
        organization: order.organization || 'default'
      };

      const docId = await createDocument('generatedDocuments', newDoc);
      
      // Update order document list
      const updatedDocs = [...existingDocs, {
        id: docId,
        name: type.replace(/([A-Z])/g, ' $1').trim(),
        type,
        status: 'pending',
        uploadedAt: Timestamp.now(),
        uploadedBy: 'System'
      }];

      await updateDocument('orders', order.id, { documents: updatedDocs });

      // Notify user
      await this.createNotification(
        order.assignedUserId,
        'Document Auto-Generated',
        `A new ${type} has been automatically generated for order ${order.orderNumber}.`,
        'success',
        order.id,
        'order',
        order.organization
      );
    } catch (error) {
      console.error('Error in autoGenerateDoc:', error);
    }
  },

  /**
   * Schedules a quality test task
   */
  async scheduleQualityTest(order: ExportOrder) {
    const task: Partial<Task> = {
      title: `Quality Test: ${order.orderNumber}`,
      description: `Automated quality testing for ${order.commodity} (${order.quantity} ${order.unit})`,
      status: 'open',
      priority: 'high',
      dueDate: Timestamp.fromMillis(Date.now() + 2 * 24 * 60 * 60 * 1000), // 2 days from now
      assigneeId: order.assignedUserId,
      relatedOrderId: order.id,
      organization: order.organization
    };

    await createDocument('tasks', task);
  },

  /**
   * Logs stage transition for bottleneck analysis
   */
  async logStageTransition(order: ExportOrder, from: OrderStage, to: OrderStage) {
    const log = {
      orderId: order.id,
      fromStage: from,
      toStage: to,
      timestamp: Timestamp.now(),
      organization: order.organization
    };
    await createDocument('stageTransitions', log);
  },

  /**
   * Periodic check for system-wide automations
   * Should be called by a heartbeat or on app load
   */
  async runPeriodicChecks() {
    const now = Date.now();
    
    // 1. Check for Overdue Payments
    const payments = await getDocuments<Payment>('payments', [
      { field: 'status', operator: '==', value: 'pending' }
    ]);

    for (const payment of payments) {
      if (payment.dueDate.toMillis() < now) {
        await this.handleOverduePayment(payment);
      }
    }

    // 2. Check for Expiring Certificates (30/60/90 days)
    const orders = await getDocuments<ExportOrder>('orders');
    for (const order of orders) {
      if (order.certificates) {
        for (const cert of order.certificates) {
          const daysToExpiry = Math.ceil((cert.expiryDate.toMillis() - now) / (24 * 60 * 60 * 1000));
          if ([30, 60, 90].includes(daysToExpiry)) {
            await this.handleExpiringCertificate(order, cert, daysToExpiry);
          }
        }
      }

      // 3. Check for Bottlenecks (e.g., in 'exportDocumentation' for > 5 days)
      const daysInStage = Math.ceil((now - (order.updatedAt?.toMillis() || now)) / (24 * 60 * 60 * 1000));
      if (daysInStage > 5 && order.stage !== 'delivered' && order.stage !== 'cancelled') {
        await this.handleBottleneck(order, daysInStage);
      }
    }
  },

  async handleOverduePayment(payment: Payment) {
    await this.createNotification(
      'admin', // Or assigned user
      'Overdue Payment Alert',
      `Payment for order ${payment.orderId} is overdue. Amount: ${payment.amount} ${payment.currency}`,
      'error',
      payment.orderId,
      'order',
      payment.organization
    );

    // Create a follow-up task
    await createDocument('tasks', {
      title: `Payment Follow-up: ${payment.orderId}`,
      description: `Follow up on overdue payment of ${payment.amount} ${payment.currency}`,
      status: 'open',
      priority: 'high',
      dueDate: Timestamp.fromMillis(Date.now() + 24 * 60 * 60 * 1000),
      relatedOrderId: payment.orderId,
      organization: payment.organization
    });
  },

  async handleExpiringCertificate(order: ExportOrder, cert: any, days: number) {
    await this.createNotification(
      order.assignedUserId,
      'Certificate Renewal Alert',
      `Certificate ${cert.number} (${cert.type}) for order ${order.orderNumber} expires in ${days} days.`,
      days <= 30 ? 'error' : 'warning',
      order.id,
      'order',
      order.organization
    );
  },

  async handleBottleneck(order: ExportOrder, days: number) {
    await this.createNotification(
      order.assignedUserId,
      'Bottleneck Alert',
      `Order ${order.orderNumber} has been in ${order.stage} stage for ${days} days.`,
      'warning',
      order.id,
      'order',
      order.organization
    );
  },

  /**
   * Automatically sends shipment email to buyer
   */
  async autoSendShipmentEmail(order: ExportOrder) {
    try {
      // In a real app, we would fetch the buyer email from the company/contact record
      // For now, we'll use a placeholder or check if it's in the order
      const buyerEmail = 'buyer@example.com'; // Placeholder
      
      const email = {
        threadId: `th_${order.id}`,
        from: 'logistics@calicuttraders.com',
        to: [buyerEmail],
        subject: `Shipment Dispatched: Order #${order.orderNumber}`,
        body: `Dear Customer, your order #${order.orderNumber} for ${order.commodity} has been shipped. 
               Vessel: ${order.vesselName || 'TBA'}
               ETD: ${order.etd?.toDate().toLocaleDateString() || 'TBA'}
               ETA: ${order.eta?.toDate().toLocaleDateString() || 'TBA'}
               
               Please find the Bill of Lading and Packing List attached.`,
        attachments: [
          { name: 'Bill_of_Lading.pdf', url: '#', size: 1024 * 1024 },
          { name: 'Packing_List.pdf', url: '#', size: 512 * 1024 }
        ],
        relatedOrderId: order.id
      };

      await zohoMailService.sendEmail(email);

      await this.createNotification(
        order.assignedUserId,
        'Shipment Email Sent',
        `Shipment notification email has been automatically sent to ${buyerEmail} for order ${order.orderNumber}.`,
        'success',
        order.id,
        'order',
        order.organization
      );
    } catch (error) {
      console.error('Error in autoSendShipmentEmail:', error);
    }
  },

  async createNotification(
    userId: string, 
    title: string, 
    message: string, 
    type: Notification['type'],
    relatedId?: string,
    relatedType?: string,
    organization?: string
  ) {
    const notification: Partial<Notification> = {
      userId,
      title,
      message,
      type,
      read: false,
      timestamp: Timestamp.now(),
      relatedEntityId: relatedId,
      relatedEntityType: relatedType,
      organization: organization || 'Calicut Traders' // Fallback
    };
    await createDocument('notifications', notification);
  }
};
